stages:
  data_ingestion:
    cmd: python -m cnnClassifier.pipeline.stage_1
    deps:
      - artifacts/data_ingestion.py
      - config/config.yaml
      - src/cnnClassifier/config/configuration.py
      - src/cnnClassifier/pipeline/stage_1.py
      - src/cnnClassifier/utils/common.py
      - /Users/imac/Downloads/Chest-CT-Scan-data
    outs:
      - artifacts/data_manifest.json:
          cache: false

  prepare_base_model:
    cmd: python -m cancer.pipeline.stage_02_prepare_basemodel
    deps:
      - config/config.yaml
      - params.yaml
      - src/cancer/components/prepare_base_model.py
      - src/cancer/entity/config_entity.py
      - src/cancer/pipeline/stage_02_prepare_basemodel.py
      - config/configuration.py
      - src/cnnClassifier/utils/common.py
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model/base_model.keras
      - artifacts/prepare_base_model/base_model_updated.keras

  training:
    cmd: python -m cancer.pipeline.stage_03_model_trainer
    deps:
      - config/config.yaml
      - params.yaml
      - artifacts/data_manifest.json
      - artifacts/prepare_base_model/base_model_updated.keras
      - src/cancer/components/model_trainer.py
      - src/cancer/entity/config_entity.py
      - src/cancer/pipeline/stage_03_model_trainer.py
      - config/configuration.py
      - src/cnnClassifier/utils/common.py
      - /Users/imac/Downloads/Chest-CT-Scan-data
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.keras

  evaluation:
    cmd: python -m cancer.pipeline.stage_04_model_eval
    deps:
      - config/config.yaml
      - params.yaml
      - artifacts/data_manifest.json
      - artifacts/training/model.keras
      - src/cancer/components/model_evaluation.py
      - src/cancer/entity/config_entity.py
      - src/cancer/pipeline/stage_04_model_eval.py
      - config/configuration.py
      - src/cnnClassifier/utils/common.py
      - /Users/imac/Downloads/Chest-CT-Scan-data
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - artifacts/evaluation/scores.json:
          cache: false
